#!/usr/bin/env bash
# Steps to configure Nginx on server

# Update package lists
sudo apt-get update -y

# Install Nginx
sudo apt-get install -y nginx

# Install and enable UFW (if needed)
sudo apt-get install -y ufw
sudo ufw enable

# Allow 'Nginx HTTP' through the firewall
sudo ufw allow 'Nginx HTTP'

# Create a simple HTML page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Test Nginx configuration
sudo nginx -t

# Reload Nginx to apply changes
sudo service nginx start
