#!/usr/bin/env bash
# steps to configure nginx on server

sudo apt-get update
sudo apt-get install -y  nginx
sudo ufw "Ngnix HTTP"

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo nginx -t

sudo service nginx reload

