#!/usr/bin/env bash
# Steps to configure Nginx on server

# Update package lists
sudo apt-get update -y

# Install Nginx
sudo apt-get install -y nginx

# Install and enable UFW (if needed)
sudo apt-get install -y ufw
sudo ufw enable

# Allow 'Nginx HTTP' through the firewall
sudo ufw allow 'Nginx HTTP'

# Create a simple HTML page
echo "Hello World!" | sudo tee /var/www/html/index.html

#Performing a 301 Redirection

string-1="server_name -;\n\trewrite ^\/redirect_me https:\/\/github.com/Emmalywebcreator peermanent;"

sudo sed -i "s/server_name _;/$string-1/" /etc/nginx/sites-enabled/default

# Test Nginx configuration
sudo nginx -t


# Start Nginx to apply changes
sudo service nginx restart
